/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI570425538 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI570425533 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425536 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197610 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197602 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425534 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI738197610 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197610.node = NNI738197610;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555177.base = NTI33555167;
NTI738197610.base = NTI33555177;
NTI738197602.base = NTI738197610;
var NNI570425534 = {kind: 1, offset: "app0", len: 0, typ: NTI738197602, name: "app0", sons: null};
NTI570425534.node = NNI570425534;
NTI570425534.base = NTI33555167;
NTI570425533.base = NTI570425534;
var NNI570425536 = {kind: 1, offset: "HEX3Aup", len: 0, typ: NTI570425533, name: ":up", sons: null};
NTI570425536.node = NNI570425536;
NTI570425536.base = NTI33555167;
var NNI570425538 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "isEggHead0", len: 0, typ: NTI33554466, name: "isEggHead0", sons: null}, 
{kind: 1, offset: "character1", len: 0, typ: NTI738197602, name: "character1", sons: null}]};
NTI570425538.node = NNI570425538;
NTI570425538.base = NTI33555167;
var objectID_805306546 = [0];

function innerHEX60gensym9__background95loading_u54() {
  var result_570425399 = null;

  BeforeRet: {
    var a_570425400 = null;
    a_570425400 = {};
    a_570425400.background = "#1099bb";
    a_570425400.resizeTo = window;
    result_570425399 = a_570425400;
    break BeforeRet;
  };

  return result_570425399;

}

function innerHEX60gensym21__background95loading_u98() {
  var result_570425443 = null;

  BeforeRet: {
    var a_570425444 = null;
    a_570425444 = {};
    a_570425444.alias = "flowerTop";
    a_570425444.src = "https://pixijs.com/assets/flowerTop.png";
    result_570425443 = a_570425444;
    break BeforeRet;
  };

  return result_570425443;

}

function innerHEX60gensym32__background95loading_u129() {
  var result_570425474 = null;

  BeforeRet: {
    var a_570425475 = null;
    a_570425475 = {};
    a_570425475.alias = "eggHead";
    a_570425475.src = "https://pixijs.com/assets/eggHead.png";
    result_570425474 = a_570425475;
    break BeforeRet;
  };

  return result_570425474;

}
async function HEX3Aanonymous__background95loading_u258() {
    var Temporary1;

  var result_570425604 = null;

  BeforeRet: {
    this.isEggHead0 = !(this.isEggHead0);
    if (this.isEggHead0) {
    Temporary1 = "eggHead";
    }
    else {
    Temporary1 = "flowerTop";
    }
    
    this.character1.texture = (await PIXI.Assets.load(Temporary1));
    result_570425604 = undefined;
    break BeforeRet;
  };

  return result_570425604;

}

function HEX3Aanonymous__background95loading_u158(texture_p0) {
    var Temporary1;

    var HEX3Aenv_570425770 = null;
    HEX3Aenv_570425770 = {m_type: NTI570425538, isEggHead0: false, character1: null};
    HEX3Aenv_570425770.isEggHead0 = true;
    HEX3Aenv_570425770.character1 = (new PIXI.Sprite(texture_p0));
    HEX3Aenv_570425770.character1.anchor.set((0.5));
    HEX3Aenv_570425770.character1.x = (this.HEX3Aup.app0.screen.width / 2);
    HEX3Aenv_570425770.character1.y = (this.HEX3Aup.app0.screen.height / 2);
    HEX3Aenv_570425770.character1.eventMode = "static";
    HEX3Aenv_570425770.character1.cursor = "pointer";
    this.HEX3Aup.app0.stage.addChild((HEX3Aenv_570425770.character1));
    Temporary1 = HEX3Aanonymous__background95loading_u258.bind(HEX3Aenv_570425770); Temporary1.ClP_0 = HEX3Aanonymous__background95loading_u258; Temporary1.ClE_0 = HEX3Aenv_570425770;
    HEX3Aenv_570425770.character1.on(("pointertap"), (Temporary1));

  
}

function HEX3Aanonymous__background95loading_u92() {
    var Temporary1;

    var HEX3Aenv_570425819 = null;
    HEX3Aenv_570425819 = {m_type: NTI570425536, HEX3Aup: null};
    HEX3Aenv_570425819.HEX3Aup = this;
    document.body.appendChild(this.app0.canvas);
    PIXI.Assets.add(innerHEX60gensym21__background95loading_u98());
    PIXI.Assets.add(innerHEX60gensym32__background95loading_u129());
    PIXI.Assets.backgroundLoad(["flowerTop", "eggHead"]);
    Temporary1 = HEX3Aanonymous__background95loading_u158.bind(HEX3Aenv_570425819); Temporary1.ClP_0 = HEX3Aanonymous__background95loading_u158; Temporary1.ClE_0 = HEX3Aenv_570425819;
    PIXI.Assets.load("eggHead").then(Temporary1);

  
}
var Temporary1;
async function HEX3Aanonymous__background95loading_u27(e_p0) {
    var Temporary1;

    var HEX3Aenv_570425769 = null;
    HEX3Aenv_570425769 = {m_type: NTI570425534, app0: null};
    HEX3Aenv_570425769.app0 = (new PIXI.Application());
    Temporary1 = HEX3Aanonymous__background95loading_u92.bind(HEX3Aenv_570425769); Temporary1.ClP_0 = HEX3Aanonymous__background95loading_u92; Temporary1.ClE_0 = HEX3Aenv_570425769;
    HEX3Aenv_570425769.app0.init(innerHEX60gensym9__background95loading_u54()).then(Temporary1);

  
}
Temporary1 = HEX3Aanonymous__background95loading_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__background95loading_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
