/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var objectID_805306546 = [0];

function innerHEX60gensym17__main_u54() {
  var result_570425399 = null;

  BeforeRet: {
    var a_570425400 = null;
    a_570425400 = {};
    a_570425400.width = 800;
    a_570425400.height = 600;
    a_570425400.backgroundColor = 65280;
    a_570425400.antialias = true;
    a_570425400.resolution = 1;
    a_570425400.preference = "webgl";
    result_570425399 = a_570425400;
    break BeforeRet;
  };

  return result_570425399;

}
var Temporary1;
async function HEX3Aanonymous__main_u30(e_p0) {
    var app_570425385 = new PIXI.Application();
    (await app_570425385.init(innerHEX60gensym17__main_u54()));
    document.body.appendChild(app_570425385.canvas);
    var texture_570425499 = (await PIXI.Assets.load("assets/dog.jpg"));
    var sprite_570425500 = new PIXI.Sprite(texture_570425499);
    app_570425385.stage.addChild((sprite_570425500));

  
}
Temporary1 = HEX3Aanonymous__main_u30.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__main_u30; Temporary1.ClE_0 = null;
window.onload = Temporary1;
