/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197610 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197602 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425519 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI738197610 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197610.node = NNI738197610;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555177.base = NTI33555167;
NTI738197610.base = NTI33555177;
NTI738197602.base = NTI738197610;
var NNI570425519 = {kind: 1, offset: "anim0", len: 0, typ: NTI738197602, name: "anim0", sons: null};
NTI570425519.node = NNI570425519;
NTI570425519.base = NTI33555167;
var objectID_805306546 = [0];

function innerHEX60gensym9__spritesheet_u51() {
  var result_570425396 = null;

  BeforeRet: {
    var a_570425397 = null;
    a_570425397 = {};
    a_570425397.background = ("#1099bb");
    a_570425397.resizeTo = window;
    result_570425396 = a_570425397;
    break BeforeRet;
  };

  return result_570425396;

}

function HEX3Aanonymous__spritesheet_u228() {
    (this.anim0.rotation += 0.01);

  
}
var Temporary1;
async function HEX3Aanonymous__spritesheet_u27(e_p0) {
            var Temporary4;
    var Temporary5;

    var HEX3Aenv_570425720 = null;
    HEX3Aenv_570425720 = {m_type: NTI570425519, anim0: null};
    var app_570425382 = new PIXI.Application();
    (await app_570425382.init(innerHEX60gensym9__spritesheet_u51()));
    document.body.appendChild(app_570425382.canvas);
    ((await PIXI.Assets.load(("https://pixijs.com/assets/spritesheet/fighter.json"))));
    var frames_570425452 = [];
    Label1: {
      var i_570425457 = 0;
      var i_570425769 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570425769 < 30)) break Label3;
            i_570425457 = i_570425769;
            if ((i_570425457 < 10)) {
            Temporary4 = (("0") + (i_570425457));
            }
            else {
            Temporary4 = (i_570425457);
            }
            
            var val_570425470 = Temporary4;
            frames_570425452.push(PIXI.Texture.from(((("rollSequence00") + val_570425470) + (".png"))));;
            i_570425769 += 1;
          }
      };
    };
    HEX3Aenv_570425720.anim0 = new PIXI.AnimatedSprite(frames_570425452);
    HEX3Aenv_570425720.anim0.x = (app_570425382.screen.width / 2);
    HEX3Aenv_570425720.anim0.y = (app_570425382.screen.height / 2);
    HEX3Aenv_570425720.anim0.anchor.set((0.5));
    HEX3Aenv_570425720.anim0.animationSpeed = 0.5;
    HEX3Aenv_570425720.anim0.play();
    app_570425382.stage.addChild((HEX3Aenv_570425720.anim0));
    Temporary5 = HEX3Aanonymous__spritesheet_u228.bind(HEX3Aenv_570425720); Temporary5.ClP_0 = HEX3Aanonymous__spritesheet_u228; Temporary5.ClE_0 = HEX3Aenv_570425720;
    app_570425382.ticker.add((Temporary5));

  
}
Temporary1 = HEX3Aanonymous__spritesheet_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__spritesheet_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
