/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554447 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI570425385 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197610 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197602 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425592 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI738197610 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197610.node = NNI738197610;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555177.base = NTI33555167;
NTI738197610.base = NTI33555177;
NTI738197602.base = NTI738197610;
NTI570425385.base = NTI738197602;
var NNI570425592 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "alienContainer0", len: 0, typ: NTI738197602, name: "alienContainer0", sons: null}, 
{kind: 1, offset: "aliens1", len: 0, typ: NTI570425385, name: "aliens1", sons: null}, 
{kind: 1, offset: "count2", len: 0, typ: NTI33554447, name: "count2", sons: null}]};
NTI570425592.node = NNI570425592;
NTI570425592.base = NTI33555167;
var objectID_805306546 = [0];

function innerHEX60gensym9__cache95as95texture95optimization_u51() {
  var result_570425396 = null;

  BeforeRet: {
    var a_570425397 = null;
    a_570425397 = {};
    a_570425397.background = ("#1099bb");
    a_570425397.resizeTo = window;
    result_570425396 = a_570425397;
    break BeforeRet;
  };

  return result_570425396;

}

function onClick__cache95as95texture95optimization_u320() {
    this.alienContainer0.cacheAsTexture(((!this.alienContainer0.isCachedAsTexture)));

  
}

function HEX3Aanonymous__cache95as95texture95optimization_u361() {
    Label1: {
      var i_570425710 = 0;
      var i_570425923 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570425923 < 100)) break Label3;
            i_570425710 = i_570425923;
            var alien_570425711 = this.aliens1[i_570425710];
            (alien_570425711.rotation += 0.1);
            i_570425923 += 1;
          }
      };
    };
    (this.count2 += 0.01);
    this.alienContainer0.scale.x = Math.sin(this.count2);
    this.alienContainer0.scale.y = Math.sin(this.count2);
    (this.alienContainer0.rotation += 0.01);

  
}
var Temporary1;
async function HEX3Aanonymous__cache95as95texture95optimization_u27(e_p0) {
    var Temporary4;
    var Temporary5;

    var HEX3Aenv_570425927 = null;
    HEX3Aenv_570425927 = {m_type: NTI570425592, alienContainer0: null, aliens1: [], count2: 0.0};
    var app_570425382 = new PIXI.Application();
    (await app_570425382.init(innerHEX60gensym9__cache95as95texture95optimization_u51()));
    document.body.appendChild(app_570425382.canvas);
    ((await PIXI.Assets.load(("https://pixijs.com/assets/spritesheet/monsters.json"))));
    HEX3Aenv_570425927.aliens1 = [];
    var alienFrames_570425469 = [("eggHead.png"), ("flowerTop.png"), ("helmlok.png"), ("skully.png")];
    HEX3Aenv_570425927.count2 = 0.0;
    HEX3Aenv_570425927.alienContainer0 = new PIXI.Container();
    HEX3Aenv_570425927.alienContainer0.x = (app_570425382.screen.width / 2);
    HEX3Aenv_570425927.alienContainer0.y = (app_570425382.screen.height / 2);
    app_570425382.stage.eventMode = ("static");
    app_570425382.stage.addChild((HEX3Aenv_570425927.alienContainer0));
    Label1: {
      var i_570425552 = 0;
      var i_570425978 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570425978 < 100)) break Label3;
            i_570425552 = i_570425978;
            var frameName_570425553 = alienFrames_570425469[Math.trunc(i_570425552 % 4)];
            var alien_570425554 = PIXI.Sprite.from(frameName_570425553);
            alien_570425554.tint = (Math.random() * 16777215);
            alien_570425554.x = ((Math.random() * app_570425382.screen.width) - (app_570425382.screen.width / 2));
            alien_570425554.y = ((Math.random() * app_570425382.screen.height) - (app_570425382.screen.height / 2));
            alien_570425554.anchor.x = 0.5;
            alien_570425554.anchor.y = 0.5;
            HEX3Aenv_570425927.aliens1.push(alien_570425554);;
            HEX3Aenv_570425927.alienContainer0.addChild((alien_570425554));
            i_570425978 += 1;
          }
      };
    };
    Temporary4 = onClick__cache95as95texture95optimization_u320.bind(HEX3Aenv_570425927); Temporary4.ClP_0 = onClick__cache95as95texture95optimization_u320; Temporary4.ClE_0 = HEX3Aenv_570425927;
    app_570425382.stage.on((("pointertap")), (Temporary4));
    Temporary5 = HEX3Aanonymous__cache95as95texture95optimization_u361.bind(HEX3Aenv_570425927); Temporary5.ClP_0 = HEX3Aanonymous__cache95as95texture95optimization_u361; Temporary5.ClE_0 = HEX3Aenv_570425927;
    app_570425382.ticker.add((Temporary5));

  
}
Temporary1 = HEX3Aanonymous__cache95as95texture95optimization_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__cache95as95texture95optimization_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
