/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197610 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197602 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425571 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI738197610 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197610.node = NNI738197610;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555177.base = NTI33555167;
NTI738197610.base = NTI33555177;
NTI738197602.base = NTI738197610;
var NNI570425571 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "texture0", len: 0, typ: NTI738197602, name: "texture0", sons: null}, 
{kind: 1, offset: "time1", len: 0, typ: NTI738197602, name: "time1", sons: null}]};
NTI570425571.node = NNI570425571;
NTI570425571.base = NTI33555167;
var objectID_805306546 = [0];

function innerHEX60gensym9__animation_u51() {
  var result_570425396 = null;

  BeforeRet: {
    var a_570425397 = null;
    a_570425397 = {};
    a_570425397.autoStart = false;
    a_570425397.resizeTo = window;
    result_570425396 = a_570425397;
    break BeforeRet;
  };

  return result_570425396;

}

function innerHEX60gensym31__animation_u137() {
  var result_570425482 = null;

  BeforeRet: {
    var a_570425483 = null;
    a_570425483 = {};
    a_570425483.texture = this.texture0;
    a_570425483.time = this.time1;
    result_570425482 = a_570425483;
    break BeforeRet;
  };

  return result_570425482;

}
var Temporary1;
async function HEX3Aanonymous__animation_u27(e_p0) {
            var Temporary4;

    var HEX3Aenv_570425838 = null;
    HEX3Aenv_570425838 = {m_type: NTI570425571, texture0: null, time1: null};
    var app_570425382 = new PIXI.Application();
    (await app_570425382.init(innerHEX60gensym9__animation_u51()));
    document.body.appendChild(app_570425382.canvas);
    var spritesheet_570425448 = (await PIXI.Assets.load(("https://pixijs.com/assets/spritesheet/0123456789.json")));
    var textures_570425449 = [];
    Label1: {
      var i_570425454 = 0;
      var i_570425888 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570425888 < 10)) break Label3;
            i_570425454 = i_570425888;
            var framekey_570425467 = ((("0123456789 ") + (i_570425454)) + (".ase"));
            HEX3Aenv_570425838.texture0 = PIXI.Texture.from(framekey_570425467);
            HEX3Aenv_570425838.time1 = spritesheet_570425448.data.frames[framekey_570425467].duration;
            Temporary4 = innerHEX60gensym31__animation_u137.bind(HEX3Aenv_570425838); Temporary4.ClP_0 = innerHEX60gensym31__animation_u137; Temporary4.ClE_0 = HEX3Aenv_570425838;
            textures_570425449.push(Temporary4());;
            i_570425888 += 1;
          }
      };
    };
    var scaling_570425514 = 4;
    var slow_570425515 = new PIXI.AnimatedSprite(textures_570425449);
    slow_570425515.anchor.set((0.5));
    slow_570425515.scale.set((scaling_570425514));
    slow_570425515.animationSpeed = 0.5;
    slow_570425515.x = ((app_570425382.screen.width - slow_570425515.width) / 2);
    slow_570425515.y = (app_570425382.screen.height / 2);
    slow_570425515.play();
    app_570425382.stage.addChild((slow_570425515));
    var fast_570425617 = new PIXI.AnimatedSprite(textures_570425449);
    fast_570425617.anchor.set((0.5));
    fast_570425617.scale.set((scaling_570425514));
    fast_570425617.x = ((app_570425382.screen.width + fast_570425617.width) / 2);
    fast_570425617.y = (app_570425382.screen.height / 2);
    fast_570425617.play();
    app_570425382.stage.addChild((fast_570425617));
    app_570425382.start();

  
}
Temporary1 = HEX3Aanonymous__animation_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__animation_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
