/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197610 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197602 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425626 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI738197610 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197610.node = NNI738197610;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555177.base = NTI33555167;
NTI738197610.base = NTI33555177;
NTI738197602.base = NTI738197610;
var NNI570425626 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "circle0", len: 0, typ: NTI738197602, name: "circle0", sons: null}, 
{kind: 1, offset: "bounds1", len: 0, typ: NTI738197602, name: "bounds1", sons: null}, 
{kind: 1, offset: "focus2", len: 0, typ: NTI738197602, name: "focus2", sons: null}]};
NTI570425626.node = NNI570425626;
NTI570425626.base = NTI33555167;
var objectID_805306546 = [0];

function innerHEX60gensym7__mask95filters95blur_u51() {
  var result_570425396 = null;

  BeforeRet: {
    var a_570425397 = null;
    a_570425397 = {};
    a_570425397.resizeTo = window;
    result_570425396 = a_570425397;
    break BeforeRet;
  };

  return result_570425396;

}

function innerHEX60gensym34__mask95filters95blur_u170() {
  var result_570425515 = null;

  BeforeRet: {
    var a_570425516 = null;
    a_570425516 = {};
    a_570425516.color = 16711680;
    result_570425515 = a_570425516;
    break BeforeRet;
  };

  return result_570425515;

}

function innerHEX60gensym45__mask95filters95blur_u205() {
  var result_570425550 = null;

  BeforeRet: {
    var a_570425551 = null;
    a_570425551 = {};
    a_570425551.strength = 32;
    result_570425550 = a_570425551;
    break BeforeRet;
  };

  return result_570425550;

}

function innerHEX60gensym72__mask95filters95blur_u293() {
  var result_570425638 = null;

  BeforeRet: {
    var a_570425639 = null;
    a_570425639 = {};
    a_570425639.scaleMode = ("nearest");
    result_570425638 = a_570425639;
    break BeforeRet;
  };

  return result_570425638;

}

function innerHEX60gensym59__mask95filters95blur_u240() {
  var result_570425585 = null;

  BeforeRet: {
    var a_570425586 = null;
    a_570425586 = {};
    a_570425586.target = this.circle0;
    a_570425586.resolution = 1;
    a_570425586.frame = this.bounds1;
    a_570425586.textureSourceOptions = innerHEX60gensym72__mask95filters95blur_u293();
    result_570425585 = a_570425586;
    break BeforeRet;
  };

  return result_570425585;

}

function HEX3Aanonymous__mask95filters95blur_u392(event_p0) {
    this.focus2.position.x = (event_p0.global.x - (this.focus2.width / 2));
    this.focus2.position.y = (event_p0.global.y - (this.focus2.height / 2));

  
}
var Temporary1;
async function HEX3Aanonymous__mask95filters95blur_u27(e_p0) {
    var Temporary1;
    var Temporary2;

    var HEX3Aenv_570425926 = null;
    HEX3Aenv_570425926 = {m_type: NTI570425626, circle0: null, bounds1: null, focus2: null};
    var app_570425382 = new PIXI.Application();
    (await app_570425382.init(innerHEX60gensym7__mask95filters95blur_u51()));
    document.body.appendChild(app_570425382.canvas);
    var grassTexture_570425437 = (await PIXI.Assets.load(("https://pixijs.com/assets/bg_grass.jpg")));
    var background_570425438 = new PIXI.Sprite(grassTexture_570425437);
    app_570425382.stage.addChild((background_570425438));
    background_570425438.width = app_570425382.screen.width;
    background_570425438.height = app_570425382.screen.height;
    HEX3Aenv_570425926.circle0 = new PIXI.Graphics().circle((132), (132), (100)).fill((innerHEX60gensym34__mask95filters95blur_u170()));
    HEX3Aenv_570425926.circle0.filters = [new PIXI.BlurFilter(innerHEX60gensym45__mask95filters95blur_u205())];
    HEX3Aenv_570425926.bounds1 = new PIXI.Rectangle(0, 0, 264, 264);
    Temporary1 = innerHEX60gensym59__mask95filters95blur_u240.bind(HEX3Aenv_570425926); Temporary1.ClP_0 = innerHEX60gensym59__mask95filters95blur_u240; Temporary1.ClE_0 = HEX3Aenv_570425926;
    var texture_570425671 = app_570425382.renderer.generateTexture((Temporary1()));
    HEX3Aenv_570425926.focus2 = new PIXI.Sprite(texture_570425671);
    app_570425382.stage.addChild((HEX3Aenv_570425926.focus2));
    background_570425438.mask = HEX3Aenv_570425926.focus2;
    app_570425382.stage.eventMode = ("static");
    app_570425382.stage.hitArea = app_570425382.screen;
    Temporary2 = HEX3Aanonymous__mask95filters95blur_u392.bind(HEX3Aenv_570425926); Temporary2.ClP_0 = HEX3Aanonymous__mask95filters95blur_u392; Temporary2.ClE_0 = HEX3Aenv_570425926;
    app_570425382.stage.on((("pointermove")), (Temporary2));

  
}
Temporary1 = HEX3Aanonymous__mask95filters95blur_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__mask95filters95blur_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
