/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197610 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197602 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425552 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI738197610 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197610.node = NNI738197610;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555177.base = NTI33555167;
NTI738197610.base = NTI33555177;
NTI738197602.base = NTI738197610;
var NNI570425552 = {kind: 1, offset: "masky0", len: 0, typ: NTI738197602, name: "masky0", sons: null};
NTI570425552.node = NNI570425552;
NTI570425552.base = NTI33555167;
var objectID_805306546 = [0];

function innerHEX60gensym9__inverse95mask_u51() {
  var result_570425396 = null;

  BeforeRet: {
    var a_570425397 = null;
    a_570425397 = {};
    a_570425397.background = ("#1099bb");
    a_570425397.resizeTo = window;
    result_570425396 = a_570425397;
    break BeforeRet;
  };

  return result_570425396;

}

function innerHEX60gensym53__inverse95mask_u218() {
  var result_570425563 = null;

  BeforeRet: {
    var a_570425564 = null;
    a_570425564 = {};
    a_570425564.mask = this.masky0;
    a_570425564.inverse = true;
    result_570425563 = a_570425564;
    break BeforeRet;
  };

  return result_570425563;

}

function toFloat__system_u1582(i_p0) {
  var result_33556016 = 0.0;

    result_33556016 = i_p0;

  return result_33556016;

}

function HEX2F__system_u1594(x_p0, y_p1) {
  var result_33556029 = 0.0;

    result_33556029 = (toFloat__system_u1582(x_p0) / toFloat__system_u1582(y_p1));

  return result_33556029;

}
var Temporary1;
async function HEX3Aanonymous__inverse95mask_u27(e_p0) {
    var Temporary1;

    var HEX3Aenv_570425726 = null;
    HEX3Aenv_570425726 = {m_type: NTI570425552, masky0: null};
    var app_570425382 = new PIXI.Application();
    (await app_570425382.init(innerHEX60gensym9__inverse95mask_u51()));
    document.body.appendChild(app_570425382.canvas);
    var rect_570425493 = new PIXI.Graphics().rect((0), (0), (400), (400)).fill((("red")));
    HEX3Aenv_570425726.masky0 = new PIXI.Graphics().star((160), (160), (5), (100)).fill((("yellow")));
    HEX3Aenv_570425726.masky0.width = 240;
    HEX3Aenv_570425726.masky0.height = 240;
    Temporary1 = innerHEX60gensym53__inverse95mask_u218.bind(HEX3Aenv_570425726); Temporary1.ClP_0 = innerHEX60gensym53__inverse95mask_u218; Temporary1.ClE_0 = HEX3Aenv_570425726;
    rect_570425493.setMask((Temporary1()));
    app_570425382.stage.addChild((rect_570425493), (HEX3Aenv_570425726.masky0));
    app_570425382.stage.position.set(((HEX2F__system_u1594(window.innerWidth, 2) - 200.0)), ((HEX2F__system_u1594(window.innerHeight, 2) - 200.0)));

  
}
Temporary1 = HEX3Aanonymous__inverse95mask_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__inverse95mask_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
