/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197610 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197602 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI570425477 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI738197610 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197610.node = NNI738197610;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555177.base = NTI33555167;
NTI738197610.base = NTI33555177;
NTI738197602.base = NTI738197610;
var NNI570425477 = {kind: 1, offset: "bunny0", len: 0, typ: NTI738197602, name: "bunny0", sons: null};
NTI570425477.node = NNI570425477;
NTI570425477.base = NTI33555167;
var objectID_805306546 = [0];

function innerHEX60gensym9__transparent95background_u51() {
  var result_570425396 = null;

  BeforeRet: {
    var a_570425397 = null;
    a_570425397 = {};
    a_570425397.backgroundAlpha = 0;
    a_570425397.resizeTo = window;
    result_570425396 = a_570425397;
    break BeforeRet;
  };

  return result_570425396;

}

function HEX3Aanonymous__transparent95background_u181() {
    (this.bunny0.rotation += 0.1);

  
}
var Temporary1;
async function HEX3Aanonymous__transparent95background_u27(e_p0) {
    var Temporary1;

    var HEX3Aenv_570425642 = null;
    HEX3Aenv_570425642 = {m_type: NTI570425477, bunny0: null};
    var app_570425382 = new PIXI.Application();
    (await app_570425382.init(innerHEX60gensym9__transparent95background_u51()));
    document.body.appendChild(app_570425382.canvas);
    var texture_570425448 = (await PIXI.Assets.load(("https://pixijs.com/assets/bunny.png")));
    HEX3Aenv_570425642.bunny0 = new PIXI.Sprite(texture_570425448);
    HEX3Aenv_570425642.bunny0.anchor.set((0.5));
    HEX3Aenv_570425642.bunny0.x = (app_570425382.screen.width / 2);
    HEX3Aenv_570425642.bunny0.y = (app_570425382.screen.height / 2);
    app_570425382.stage.addChild((HEX3Aenv_570425642.bunny0));
    Temporary1 = HEX3Aanonymous__transparent95background_u181.bind(HEX3Aenv_570425642); Temporary1.ClP_0 = HEX3Aanonymous__transparent95background_u181; Temporary1.ClE_0 = HEX3Aenv_570425642;
    app_570425382.ticker.add((Temporary1));

  
}
Temporary1 = HEX3Aanonymous__transparent95background_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__transparent95background_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
