/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var objectID_805306546 = [0];

function innerHEX60gensym9__particles_u51() {
  var result_570425396 = null;

  BeforeRet: {
    var a_570425397 = null;
    a_570425397 = {};
    a_570425397.autoStart = false;
    a_570425397.resizeTo = window;
    result_570425396 = a_570425397;
    break BeforeRet;
  };

  return result_570425396;

}
var Temporary1;
async function HEX3Aanonymous__particles_u27(e_p0) {
    var app_570425382 = new PIXI.Application();
    (await app_570425382.init(innerHEX60gensym9__particles_u51()));
    document.body.appendChild(app_570425382.canvas);
    ((await PIXI.Assets.load(("https://pixijs.com/assets/spritesheet/mc.json"))));
    var explosionTextures_570425448 = [];
    Label1: {
      var i_570425453 = 0;
      var i_570425722 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570425722 < 26)) break Label3;
            i_570425453 = i_570425722;
            var texture_570425466 = PIXI.Texture.from(((("Explosion_Sequence_A ") + ((i_570425453 + 1))) + (".png")));
            explosionTextures_570425448.push(texture_570425466);;
            i_570425722 += 1;
          }
      };
    };
    Label4: {
      var i_570425475 = 0;
      var i_570425725 = 0;
      Label5: {
          Label6: while (true) {
          if (!(i_570425725 < 50)) break Label6;
            i_570425475 = i_570425725;
            var explosion_570425476 = new PIXI.AnimatedSprite(explosionTextures_570425448);
            explosion_570425476.x = (Math.random() * app_570425382.screen.width);
            explosion_570425476.y = (Math.random() * app_570425382.screen.height);
            explosion_570425476.anchor.set((0.5));
            explosion_570425476.rotation = (Math.random() * Math.PI);
            explosion_570425476.scale.set(((0.75 + (Math.random() * 0.5))));
            explosion_570425476.gotoAndPlay((((Math.random() * 26) | 0)));
            app_570425382.stage.addChild((explosion_570425476));
            i_570425725 += 1;
          }
      };
    };
    app_570425382.start();

  
}
Temporary1 = HEX3Aanonymous__particles_u27.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__particles_u27; Temporary1.ClE_0 = null;
window.onload = Temporary1;
